from typing import Dict, Any
from src.schemas import EduPlan


def mock_plan(goal: str, target_audience: str, duration_minutes: int) -> EduPlan:
    """
    Create a mock educational plan that ALWAYS matches the requested total duration.
    This simulates what later will be generated by an AI model, but with deterministic rules.
    """

    # Fixed first two activities
    a1 = 15
    a2 = 20

    # The last activity automatically fills the remaining time
    remaining = max(duration_minutes - (a1 + a2), 5)

    data: Dict[str, Any] = {
        "meta": {
            "theme": goal,
            "target_audience": target_audience,
            "duration_total_minutes": duration_minutes,
        },
        "learning_objectives": [
            "Understand the basic concept of Artificial Intelligence",
            "Recognize real-world examples of AI",
            "Work collaboratively in a small group",
        ],
        "activities": [
            {
                "id": "A1",
                "title": "Icebreaker discussion",
                "description": "Students discuss where they encounter AI in daily life.",
                "duration_minutes": a1,
                "materials": ["whiteboard", "markers"],
                "skills_targeted": ["communication", "critical thinking"],
                "assessment_method": "Group discussion and quick feedback",
            },
            {
                "id": "A2",
                "title": "AI concept explanation",
                "description": "Teacher explains how AI systems learn from data.",
                "duration_minutes": a2,
                "materials": ["slides"],
                "skills_targeted": ["digital literacy"],
                "assessment_method": "Students explain the concept in their own words",
            },
            {
                "id": "A3",
                "title": "Hands-on group activity",
                "description": "Small groups complete a simple classification task to understand patterns and data.",
                "duration_minutes": remaining,
                "materials": ["printed cards", "A4 sheets"],
                "skills_targeted": ["teamwork", "observation"],
                "assessment_method": "Groups justify their classification criteria",
            },
        ],
        "risk_analysis": [
            {"risk": "Students lose attention", "mitigation": "Keep activities interactive and switch pace every 10–15 minutes"},
            {"risk": "Concepts feel too abstract", "mitigation": "Use simple analogies and concrete examples"},
        ],
        "commercial_summary": "Interactive workshop introducing AI concepts through discussion and a practical group activity.",
    }

    return EduPlan.model_validate(data)